### PR TITLE
Require sassc-rails if available, fallback to sass-rails otherwise

### PR DESCRIPTION
**Pull request by xijo**
Attempt to solve issue #112

### CODE REVIEW

**Comment by MichaelSp** [comment]
Please merge and release

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by garettarrowood** [comment]
This would be very helpful. Can someone review and merge? We'd prefer not to fork.

**Comment by Fudoshiki** [comment]
What current state?

**Comment by rsl** [comment]
would love to see this in the official version. already in my fork.

**Comment by n-rodriguez** [comment]
Hi! Any news?

**Comment by jsmestad** [comment]
FYI #141 I just opened solves this by just skipping the require of `sass-rails` or `sassc-rails` all together.

**Comment by supercodepoet** [comment]
Should be fixed in 5.5.0.1

**Pull request closed without merging**
