### PR TITLE
Updated font-awesome to 4.6.1

### LINKED ISSUE #115: Please update to 4.6.0
Sorry for marking this as an issue, can we please have version 4.6.0?

### PR DESCRIPTION
**Pull request by supernova32**
This pull request updates all assets of FontAwesome to 4.6.1, as well as the version of the Gem.

Changes have been tested locally.

Fixes #115

### CODE REVIEW

**Comment by blendsdk** [comment]
Please update to 4.6.1

**Comment by supernova32** [comment]
@blendsdk it is 4.6.1

**Comment by blendsdk** [comment]
Thank you:)

**Comment by afurm** [comment]
Please, do the merge :smile:

**Pull request merged**
