### PR TITLE
Us/4.6.3

### PR DESCRIPTION
**Pull request by mfo**
needed the instagram brand new icon ; hope it helps :-)

### CODE REVIEW

**Comment by nicolaslazartekaqui** [comment]
🆙

**Comment by nicolaslazartekaqui** [comment]
@mfo I'll use your PR on my fork while it is not accepted into the official project, thanks :)

**Comment by carlosbutler** [comment]
+1

**Comment by itanex** [comment]
When is this likely to merge?

**Comment by cachesclay** [comment]
^bump

**Pull request closed without merging**
